services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8081      # Changed from 8080 to 8081
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./incomplete:/incomplete
    ports:
      - 8081:8081            # Map host 8081 to container 8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped