services:
  flask-app:
    build: ./cours
    image: flask_app
    deploy:
      replicas: 5
    volumes:
      - ./cours:/app/cours
    develop:
      watch:
        - action: sync
          path: .
          target: /app/cours
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
volumes:
  mongo_data:
