# Generated by Django 5.2.4 on 2025-07-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_classe_name_alter_classe_title_alter_post_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
