# Generated by Django 5.2.4 on 2025-07-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_classe_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
