# Generated by Django 5.2.4 on 2025-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_datetime',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
