services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: ./project
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: mydb
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    volumes:
      - ./project:/app/project
    develop:
      watch:
        - action: sync
          path: .
          target: /app/project
volumes:
  mysql-data:
